data:
  mysql:
    host: localhost
    port: 3309
    database: soft
    username: root
    password: jscomet_@_21232
  redis:
    host: localhost
    port: 6380
    password: jscomet_@_21232

app:
  domain: http://localhost
  back:
    url: http://localhost:8080